name: forcast
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.0
  get: ^4.7.2
  flutter_svg: ^2.2.0
  supabase_flutter: ^2.5.6
  crypto: ^3.0.3
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.1.2
  workmanager: ^0.9.0+3
  path_provider: ^2.1.3
  screenshot: ^3.0.0
  gal: ^2.3.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  intl: ^0.20.2
  timeago: ^3.7.1
  flutter_icon_snackbar: ^1.2.1
  permission_handler: ^11.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/


  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/SfProDisplay.ttf


